In [1]:
import torch
torch.__version__

'2.4.0+cu121'

In [3]:
x = torch.arange(12)
print(x.shape)
x

torch.Size([12])


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
x.numel()

12

In [7]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
x.reshape(3,-1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
torch.randn(3, 4)

tensor([[-1.4802,  0.7854,  0.0078,  0.3564],
        [ 2.6973, -0.1713, -0.4338,  1.4095],
        [-2.0189,  0.0998, -0.1107, -2.5541]])

In [12]:
torch.tensor([[1.0, 2, 4], [3, 4, 5]])

tensor([[1., 2., 4.],
        [3., 4., 5.]])

## 2.1.2. 运算符

In [13]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x+y

tensor([ 3.,  4.,  6., 10.])

In [14]:
x-y

tensor([-1.,  0.,  2.,  6.])

In [15]:
x/y

tensor([0.5000, 1.0000, 2.0000, 4.0000])

In [16]:
x**y

tensor([ 1.,  4., 16., 64.])

In [17]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

## 张量连结（concatenate）

In [18]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0)  # 按行拼接

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [19]:
torch.cat((X, Y), dim=1)  # 按列拼接

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [20]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [21]:
X.sum()

tensor(66.)

## 2.1.3. 广播机制

In [22]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [23]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 2.1.4. 索引和切片¶

In [30]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [31]:
X[-1],X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [32]:
X[1,2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [34]:
X[1:3,:] = 12
X

tensor([[ 0.,  1.,  2.,  3.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.]])

## 2.1.5. 节省内存

In [35]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [36]:
id(X)

129440889523312

In [37]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 129440889572384
id(Z): 129440889572384


In [38]:
before = id(X)
X += Y
id(X) == before

True

## 2.1.6. 转换为其他Python对象

In [39]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [41]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)